// COMPONENTS
// export { default as About } from './About'
// export { default as AboutCard } from './AboutCard'
// export { default as AboutStats } from './AboutStats'
// export { default as Button } from './Button'
// export { default as Featured } from './Featured'
// export { default as Footer } from './Footer'
// export { default as Header } from './Header'
// export { default as Hero } from './Hero'
// export { default as Nav } from './Nav'
// export { default as ShoeCard } from './ShoeCard'
// export { default as Shop } from './Shop'
// export { default as Subscription } from './Subscription'


// ASSETS
export { default as about } from '/assets/images/about.jpg'
export { default as featured1 } from '/assets/images/featured1.png'
export { default as featured2 } from '/assets/images/featured2.png'
export { default as featured3 } from '/assets/images/featured3.png'
export { default as featured4 } from '/assets/images/featured4.png'
export { default as footer } from '/assets/images/footer.jpg'
export { default as pattern } from '/assets/images/pattern.png'
export { default as product1 } from '/assets/images/product-1.jpg'
export { default as product2 } from '/assets/images/product-2.jpg'
export { default as product3 } from '/assets/images/product-3.jpg'
export { default as product4 } from '/assets/images/product-4.jpg'
export { default as product5 } from '/assets/images/product-5.jpg'
export { default as product6 } from '/assets/images/product-6.jpg'
export { default as product7 } from '/assets/images/product-7.jpg'
export { default as product8 } from '/assets/images/product-8.jpg'
export { default as shoe1 } from '/assets/images/shoe1.png'
export { default as shoe2 } from '/assets/images/shoe2.png'
export { default as shoe3 } from '/assets/images/shoe3.png'
export { default as thumbnail1 } from '/assets/images/thumbnail1.png'
export { default as thumbnail2 } from '/assets/images/thumbnail2.png'
export { default as thumbnail3 } from '/assets/images/thumbnail3.png'
